#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
# Gradle wrapper — JAR 未配置でも distributionUrl から自動取得。
#

# Attempt to set APP_HOME
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done
APP_HOME=`dirname "$PRG"`
APP_HOME=`cd "$APP_HOME" && pwd`

# Determine the Java command to use
if [ -n "$JAVA_HOME" ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
    if [ ! -x "$JAVACMD" ] ; then
        echo "ERROR: JAVA_HOME is set but java is not found at $JAVACMD"
        exit 1
    fi
else
    JAVACMD="java"
fi

# Build classpath
WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -e "$WRAPPER_JAR" ]; then
    echo "Downloading Gradle wrapper JAR..."
    DIST_URL=$(grep distributionUrl "$APP_HOME/gradle/wrapper/gradle-wrapper.properties" | sed 's/.*=//; s/\\//g')
    WRAPPER_URL="https://raw.githubusercontent.com/gradle/gradle/v8.11.1/gradle/wrapper/gradle-wrapper.jar"
    if command -v curl > /dev/null 2>&1; then
        curl -sL -o "$WRAPPER_JAR" "$WRAPPER_URL"
    elif command -v wget > /dev/null 2>&1; then
        wget -q -O "$WRAPPER_JAR" "$WRAPPER_URL"
    else
        echo "ERROR: curl or wget required to download gradle-wrapper.jar"
        exit 1
    fi
fi

exec "$JAVACMD" \
    $JAVA_OPTS \
    -classpath "$WRAPPER_JAR" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
